### PR TITLE
Put a test file for hardware in!

### PR DESCRIPTION
**Pull request by johnisanerd**
This makes testing hardware issues much easier.

### CODE REVIEW

**Comment by johnisanerd** [comment]
@googlebot I signed it!

**Comment by johnisanerd** [comment]
@romankhar can you take a look at this?

**Comment by johnisanerd** [comment]
Just checking in, anyone reviewed this?

**Comment by romankhar** [comment]
I accepted PR and moved and renamed the file - thank you for your
contribution!
https://github.com/GoogleCloudPlatform/cloud-derby/blob/master/car/test_hardware.py

Roman Kharkovski
Phone: +1-412-267-7662
Blog: http://RomanKharkovski.com

**Pull request merged**
